### ISSUE TITLE
Support for lower GL versions?

### ISSUE THREAD

**Issue by pupcraft** [Shinmera/beamer#1]
When I run
```
(beamer:start-slideshow (merge-pathnames "test/test.lisp" (asdf:system-source-directory :beamer)))
```

it gives
```Couldn't find function glCreateTextures```

```glCreateTextures``` is only for GL 4.5

**Comment by Shinmera** [comment]
I don't use glCreateTextures.

**Comment by pupcraft** [comment]
Ah yes but you do, I got it to work. See this: https://github.com/Shirakumo/trial/pull/18
